// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyJNR656CVaMCUt9RW77vcTnRYSLINJo',
    appId: '1:736050473458:web:4e049a45dd642b3ef2e36b',
    messagingSenderId: '736050473458',
    projectId: 'sizannew02',
    authDomain: 'sizannew02.firebaseapp.com',
    storageBucket: 'sizannew02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9J4RGCIBTtvgAory1wrYzyKC_44UhCJA',
    appId: '1:736050473458:android:0e7b5eb849573ce6f2e36b',
    messagingSenderId: '736050473458',
    projectId: 'sizannew02',
    storageBucket: 'sizannew02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsaaS2hjMBn7btlZw0rkWHfQqDxYeAZ4',
    appId: '1:736050473458:ios:5ebd0d3dc44e7506f2e36b',
    messagingSenderId: '736050473458',
    projectId: 'sizannew02',
    storageBucket: 'sizannew02.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsaaS2hjMBn7btlZw0rkWHfQqDxYeAZ4',
    appId: '1:736050473458:ios:5ebd0d3dc44e7506f2e36b',
    messagingSenderId: '736050473458',
    projectId: 'sizannew02',
    storageBucket: 'sizannew02.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlyJNR656CVaMCUt9RW77vcTnRYSLINJo',
    appId: '1:736050473458:web:d830f11b34a699eaf2e36b',
    messagingSenderId: '736050473458',
    projectId: 'sizannew02',
    authDomain: 'sizannew02.firebaseapp.com',
    storageBucket: 'sizannew02.firebasestorage.app',
  );
}
